# Generated by Django 3.1.1 on 2020-09-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
